#!/bin/bash
echo "ALX School is so cool!"
^C
root@630a82991ec1:/alx-pre_course/0x01-git/bash# clear
root@630a82991ec1:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
echo "School"
root@630a82991ec1:/alx-pre_course/0x01-git/bash# git add .
root@630a82991ec1:/alx-pre_course/0x01-git/bash# git commit -m "Starting to code today, so cool"

